### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by jordanwillis** [deanarron/colmar#3]
Your CSS was very will crafted as well.  I typically spend a lot of time explaining to students in my project reviews about the importance of DRY (don't repeat yourself) CSS and techniques for how to eliminate duplicated properties/styles.  In your case, I can tell that you had DRY in mind because I see evidence of many of the same techniques used in your CSS.  This ability will pay huge dividends on future projects!

**Comment by deanarron** [comment]
Thanks so much, Jordan!
