### ISSUE TITLE
Summary: Grade = Exceeds Expectations

### ISSUE THREAD

**Issue by jordanwillis** [deanarron/colmar#4]
Overall you did an outstanding job on this project and this very well could be one of the best capstone projects I have reviewed in a very long time!  Not only was the implementation great, but the attention to detail with regard to accessibility, semantic HTML. code format and style, and DRY CSS made it pretty darn near perfect.

My only advise is to take a look at how some elements such as `<img>` react to role="presentation" so that you can keep that in mind for the future.

Keep up the awesome work!

**Comment by deanarron** [comment]
Wow! Thanks so much, Jordan, this is really, very appreciated!
